apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: summit-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/kvenkata986/shanghai-summit.git
